# Generated by Django 4.1.3 on 2022-11-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description1_az',
            field=models.TextField(max_length=2000, null=True, verbose_name='Qısa məzmun'),
        ),
        migrations.AddField(
            model_name='news',
            name='description1_en',
            field=models.TextField(max_length=2000, null=True, verbose_name='Qısa məzmun'),
        ),
        migrations.AddField(
            model_name='news',
            name='description2_az',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Məzmun1'),
        ),
        migrations.AddField(
            model_name='news',
            name='description2_en',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Məzmun1'),
        ),
        migrations.AddField(
            model_name='news',
            name='description3_az',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Məzmun2'),
        ),
        migrations.AddField(
            model_name='news',
            name='description3_en',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Məzmun2'),
        ),
        migrations.AddField(
            model_name='news',
            name='description4_az',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Məzmun3'),
        ),
        migrations.AddField(
            model_name='news',
            name='description4_en',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Məzmun3'),
        ),
        migrations.AddField(
            model_name='news',
            name='description5_az',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Məzmun4'),
        ),
        migrations.AddField(
            model_name='news',
            name='description5_en',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Məzmun4'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_az',
            field=models.CharField(max_length=256, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Başlıq'),
        ),
    ]
