# Generated by Django 4.1.3 on 2022-11-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_description1_az_news_description1_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pdf',
            field=models.FileField(blank=True, upload_to='pdf'),
        ),
    ]
