# Generated by Django 4.1.3 on 2022-11-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pdf_title',
            field=models.CharField(default=1, max_length=256, verbose_name='Başlıq'),
            preserve_default=False,
        ),
    ]
