# Generated by Django 4.1.3 on 2022-11-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_pdf_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pdf_title',
            field=models.CharField(max_length=256, verbose_name='Pdf adı'),
        ),
    ]
