# Generated by Django 4.1.3 on 2022-11-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Ad Soyad')),
                ('number', models.CharField(max_length=20, verbose_name='Telefon nömrəsi')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('subject', models.CharField(max_length=150, verbose_name='Mövzu')),
                ('messege', models.TextField(max_length=2000, verbose_name='Mesaj')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Ad')),
                ('surname', models.CharField(max_length=256, verbose_name='Soyad')),
                ('father_name', models.CharField(max_length=256, verbose_name='Ata adı')),
                ('gender', models.CharField(choices=[('M', 'Kişi'), ('F', 'Qadın')], default='Male', max_length=20, verbose_name='Cins')),
                ('passport_number', models.CharField(max_length=20, verbose_name='Şəxsiyyət vəsiqəsinin seriya və nömrəsi')),
                ('passport_fin_number', models.CharField(max_length=20, verbose_name='Şəxsiyyət vəsiqəsinin indentifikasiya (FİN) kodu:')),
                ('born', models.DateField(verbose_name='Doğum tarixi')),
                ('place_of_birth', models.CharField(max_length=20, verbose_name='Doğulduğu yer')),
                ('actual_residence', models.CharField(max_length=256, verbose_name='Faktiki yaşayış yeri')),
                ('home_phone_number', models.CharField(max_length=20, verbose_name='Ev nömrəsi')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Mobil nömrə')),
                ('email', models.EmailField(max_length=256, verbose_name='Email')),
                ('areas_of_activity', models.CharField(max_length=5000, verbose_name='Fəaliyyət istiqaməti')),
                ('work_time', models.CharField(max_length=5000, verbose_name='Qeyd etdiyi istiqamət üzrə bu müddətdir ki, fəaliyyət göstərir')),
                ('establishment', models.CharField(max_length=5000, verbose_name='Fəaliyyət istiqamətində təsisatın adı')),
                ('adress', models.CharField(max_length=5000, verbose_name='Təsisatın yerləşdiyi ünvan')),
                ('facility_site', models.CharField(max_length=50, verbose_name='Təsisatın media və əlaqə vasitələri - Sayt')),
                ('facility_phone_number', models.CharField(max_length=50, verbose_name='Təsisatın media və əlaqə vasitələri - Telefon')),
                ('facility_mail', models.EmailField(max_length=50, verbose_name='Təsisatın media və əlaqə vasitələri - E-poçt')),
                ('project', models.TextField(max_length=5000, verbose_name='Təsisat olaraq bu günə kimi qeyd edilən istiqamət üzrə hansı layihələri həyata keçirib')),
                ('project_part', models.TextField(max_length=5000, verbose_name='İcra etdiyim layihələrin hansı hissəsinin donor qurumlar və ya öz şəxsi hesabıma keçirilir')),
                ('purpose', models.TextField(max_length=5000, verbose_name='Sizə üzv olmaqda məqsəd və gözləntilərim')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
